// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_lines
Rcpp::CharacterVector read_lines(std::string const& filename, Rcpp::NumericVector const& lines, char sep);
RcppExport SEXP PhenotypeSimulator_read_lines(SEXP filenameSEXP, SEXP linesSEXP, SEXP sepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string const& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector const& >::type lines(linesSEXP);
    Rcpp::traits::input_parameter< char >::type sep(sepSEXP);
    rcpp_result_gen = Rcpp::wrap(read_lines(filename, lines, sep));
    return rcpp_result_gen;
END_RCPP
}
