# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Scan file for specific line numbers
#' 
#' @param filename /path/to/chromosomefile [string]
#' @param lines vector of line numbers [integer] to be read
#' @param sep [string] end-of-line delimiter
read_lines <- function(filename, lines, sep = '\n') {
    .Call(`_PhenotypeSimulator_read_lines`, filename, lines, sep)
}

